make toxic everglades great again
GTNewHorizons/GTNH-Intergalactic pull request #29
Opened 2023-05-14 22:56 UTC by Fiyorin

allows these ores to be mined:

koboldite
crocoite
gadolinite (Y)
lepersonnite
zircon
lautarite
honeaite
alburnite
strange
rare earth i
rare earth ii
rare earth iii

2023-05-15 19:50 UTC, Fiyorin commented
add lutetium ore for plutonium 239 plasma

2023-05-18 13:51 UTC, minecraft7771 requested changes

2023-05-18 13:51 UTC, minecraft7771 commented on src/main/java/com/gtnewhorizons/gtnhintergalactic/recipe/SpaceMiningRecipes.java
> +                    new int[] { 700, 500, 1500, 1500, 1000, 500, 1000, 700, 1000, 1000, 1000 },
Please adjust chances so the sum is 100.00%

2023-05-18 19:58 UTC, minecraft7771 approved these changes

2023-05-18 19:58 UTC, merged